# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.two_factor.u2f:
        class: AppBundle\Security\TwoFactor\U2FService
        arguments: ["@router", "@request_stack"]
    app.two_factor.u2f_provider:
        class: AppBundle\Security\TwoFactor\Provider\U2FProvider
        arguments: ["@templating", "@app.two_factor.u2f", "@form.factory", "@doctrine.orm.entity_manager"]
        tags:
            - { name: scheb_two_factor.provider, alias: u2f }